require 'five_leaves/prime_util.rb'
require 'five_leaves/sum.rb'
require 'five_leaves/range_util.rb'
require 'five_leaves/maximize.rb'
require 'five_leaves/lazy_enum.rb'
require 'five_leaves/enum_util.rb'
require 'five_leaves/palindromic.rb'
require 'five_leaves/items_following.rb'
